Blog.Web/Models/ErrorViewModel.cs
namespace Blog.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Blog.Web/Areas/Admin/ViewComponents/DashboardHeaderViewComponent.cs
using AutoMapper;
using Blog.Entity.DTOs.Users;
using Blog.Entity.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.Areas.Admin.ViewComponents;

public class DashboardHeaderViewComponent : ViewComponent
{
    private readonly UserManager<AppUser> userManager;
    private readonly IMapper mapper;

    public DashboardHeaderViewComponent(UserManager<AppUser> userManager,IMapper mapper)
    {
        this.userManager = userManager;
        this.mapper = mapper;
    }
    public async Task<IViewComponentResult> InvokeAsync()
    {
        var loggedInUser = await userManager.GetUserAsync(HttpContext.User);
        var map = mapper.Map<UserDto>(loggedInUser);

        var role = string.Join("", await userManager.GetRolesAsync(loggedInUser));
        map.Role = role;

        return View(map);
    }
}

Blog.Web/Areas/User/Controllers/CommentController.cs
using AutoMapper;
using Blog.Data.UnitOfWorks;
using Blog.Entity.DTOs.Comments;
using Blog.Service.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using Blog.Entity.Entities;

namespace Blog.Web.Areas.User.Controllers.CommentController;

[Area("User")]
[Route("User/[controller]/[action]")]

public class CommentController : Controller
{
    private readonly ICommentService _commentService;
    private readonly IToastNotification _toastNotification;
    private readonly IMapper _mapper;
    private readonly IUnitOfWork _unitOfWork;

    public CommentController(ICommentService commentService, IToastNotification toastNotification, IMapper mapper, IUnitOfWork unitOfWork)
    {
        _commentService = commentService;
        _toastNotification = toastNotification;
        _mapper = mapper;
        _unitOfWork = unitOfWork;
    }
    [HttpPost]
    public async Task<IActionResult> SendComment(Guid articleId, CommentAddDto commentAddDto)
    {
    
        if (ModelState.IsValid)
        {
            var map = _mapper.Map<Comment>(commentAddDto);
            map.ArticleId = articleId;
            await _unitOfWork.GetRepository<Comment>().AddAsync(map);
            await _unitOfWork.SaveAsync();
            _toastNotification.AddSuccessToastMessage("Yorumunuz başarıyla gönderildi!");
        }
        else
        {
            _toastNotification.AddErrorToastMessage("Yorumunuz gönderilemedi.");
        }

        return RedirectToAction("ArticleDetail", "Home", new {area="", articleId});
    }
}

Blog.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Blog.Data.UnitOfWorks;
using Blog.Entity.DTOs.Comments;
using Blog.Entity.Entities;
using Blog.Service.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using Blog.Web.Models;
using NToastNotify;

namespace Blog.Web.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IArticleService _articlecleService;
    private readonly IHttpContextAccessor _contextAccessor;
    private readonly IUnitOfWork _unitOfWork;
    private readonly ICommentService _commentService;
    private readonly IToastNotification _toastNotification;

    public HomeController(ILogger<HomeController> logger, IArticleService articlecleService, 
        IHttpContextAccessor contextAccessor, IUnitOfWork unitOfWork, ICommentService commentService
        ,IToastNotification toastNotification)
    {
        _logger = logger;
        _articlecleService = articlecleService;
        _contextAccessor = contextAccessor;
        _unitOfWork = unitOfWork;
        _commentService = commentService;
        _toastNotification = toastNotification;
    }

    [HttpGet]
    public async Task<IActionResult> Index(Guid? categoryId, int currentPage = 1, int pageSize = 3, bool isAscending = false)
    {
        var articles = await _articlecleService.GetAllByPaginationAsync(categoryId, currentPage, pageSize, isAscending);
        return View(articles);
    }
    [HttpGet]
    public async Task<IActionResult> Search(string keyword, int currentPage = 1, int pageSize = 3, bool isAscending = false)
    {
        var articles = await _articlecleService.SearchAsync(keyword, currentPage, pageSize, isAscending);
        return View(articles);
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
    public IActionResult Contact()
    {
        return View();
    }
    public IActionResult About()
    {
        return View();
    }

    public async Task<IActionResult> ArticleDetail(Guid articleId)
    {
        var ipAddress = _contextAccessor.HttpContext.Connection.RemoteIpAddress.MapToIPv4().ToString();
        
        var articeVisitors = await _unitOfWork.GetRepository<ArticleVisitor>().GetAllAsync(null, x => x.Visitor, y => y.Article);
        var article = await _unitOfWork.GetRepository<Article>().GetAsync(x => x.Id == articleId);

        var result = await _articlecleService.GetArticleWithCategoryNonDeletedAsync(articleId);

        var visitor = await _unitOfWork.GetRepository<Visitor>().GetAsync(x => x.IpAddress == ipAddress);

        var addArticleVisitors = new ArticleVisitor(article.Id,visitor.Id);

        if (articeVisitors.Any(x =>
                x.VisitorId == addArticleVisitors.VisitorId && x.ArticleId == addArticleVisitors.ArticleId))
        {
            result.Comments = await _commentService.GetCommentsWithArticleId(articleId);
            return View(result);
        }
        else
        {
            await _unitOfWork.GetRepository<ArticleVisitor>().AddAsync(addArticleVisitors);
            article.ViewCount += 1;
            await _unitOfWork.GetRepository<Article>().UpdateAsync(article);
            await _unitOfWork.SaveAsync();
            result.ViewCount++;
        }

        result.Comments = await _commentService.GetCommentsWithArticleId(articleId);
        return View(result);
    }

    

    
}

Blog.Web/ViewComponents/HomeCategoriesViewComponent.cs
using Blog.Service.Services.Concretes;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.ViewComponents;

public class HomeCategoriesViewComponent : ViewComponent
{
    private readonly ICategoryService _categoryService;

    public HomeCategoriesViewComponent(ICategoryService categoryService)
    {
        _categoryService = categoryService;
    }

    //Invoke anlamı çağırmak zaten view'i çağıracak metodumuz budur
    public async Task<IViewComponentResult> InvokeAsync()
    {
        var categories = await _categoryService.Get24CategoriesDeletedAsync();
        return View(categories);
    }
}

Blog.Web/ViewComponents/HomeRecentArticlesViewComponent.cs
using Blog.Service.Services.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.ViewComponents;

public class HomeRecentArticlesViewComponent : ViewComponent
{
    private readonly IArticleService _articleService;

    public HomeRecentArticlesViewComponent(IArticleService articleService)
    {
        _articleService = articleService;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var recentArticles = await _articleService.GetRecentArticlesAsyncNonDeleted();
        return View(recentArticles);
    }
    
}

Blog.Web/Areas/Admin/Views/Article/Add.cshtml
@model ArticleAddDto
<div class="container-xxl flex-grow-1 container-p-y">

    <h4 class="fw-bold py-3 mb-4">
        <span class="text-muted fw-light">Makale Yönetimi /</span> Makale Ekle
    </h4>

    <div class="row">
        <div class="col-md-12">
            <div class="card mb-4">
                <h5 class="card-header"></h5>
                <form asp-controller="Article" asp-action="Add" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="CategoryId">Kategori</label>
                            <a class="btn text-primary float-end" data-bs-toggle="modal" data-bs-target="#exampleModalCenter">
                                Kategori Ekle <i class="bx bx-plus"></i>
                            </a>
                            <select id="categoryList" class="form-control" asp-for="CategoryId" asp-items="@(new SelectList(Model.Categories, "Id", "Name"))"></select>
                            <span asp-validation-for="CategoryId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Title" class="form-label">Başlık</label>
                            <input asp-for="Title" type="text" class="form-control mb-3" placeholder="Lütfen başlık giriniz." aria-describedby="defaultFormControlHelp">
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Content" class="form-label">İçerik</label>
                            <textarea asp-for="Content" class="form-control mb-3" style="min-height:300px;" placeholder="İçerik" aria-describedby="defaultFormControlHelp"></textarea>
                            <span asp-validation-for="Content" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Photo" class="form-label">Resim Seçiniz</label>
                            <input asp-for="Photo" type="file" accept="image/*" class="form-control mb-3" id="default-FromControlInput" aria-describedby="defaultFormControlHelp">
                            <span asp-validation-for="Photo" class="text-danger"></span>
                        </div>                            
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">Kaydet</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Hızlı Kategori Ekleme</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label class="d-block form-label">Kategorİ İsmİ</label>
                            <input class="form-control" type="text" id="categoryName"/>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Kapat</button>
                <button type="button" data-keyboard="false" class="btn btn-primary" id = "btnSave">Değişikleri Kaydet</button>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script src="~/js/categoryAdd.js"></script>
    <script>
    var app = app || {};
    app.Urls = app.Urls || {};
    
    app.Urls.baseUrl = '@Url.Content("~")';
    app.Urls.categoryAddUrl = "@(Url.Action("AddWithAjax", "Category"))";
    app.Urls.articleAddUrl = "@(Url.Action("Add", "Article"))";
    </script>
}

Blog.Web/Areas/Admin/Views/Article/DeletedArticles.cshtml
@model List<ArticleDto>

<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4">
        <span class="text-muted fw-light">Çöp Kutusu /</span> Makaleler
    </h4>

    <!-- Basic Bootstrap Table -->
    <div class="card">
        <div class="table-responsive text-nowrap m-5">
            
            
            <table class="table table-bordered" id="articlesTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>Başlık</th>
                    <th>Kategori</th>
                    <th>Oluşturulma Tarihi</th>
                    <th>Oluşturan</th>
                    <th>Durum</th>
                    <th>İşlemler</th>
                </tr>
                </thead>
                @* <tfoot> *@
                @*     <tr> *@
                @*         <th>Başlık</th> *@
                @*         <th>Kategori</th> *@
                @*         <th>Oluşturulma Tarihi</th> *@
                @*         <th>Oluşturan</th> *@
                @*         <th>Durum</th> *@
                @*         <th>İşlemler</th> *@
                @*     </tr> *@
                @* </tfoot> *@
                <tbody class="table-border-bottom-0">
                @foreach (var article in Model)
                {
                    <tr name="@article.Id">
                        <td>@article.Title</td>
                        <td>@article.Category.Name</td>
                        <td>@article.CreatedDate.ToShortDateString()</td>
                        <td>@article.CreatedBy</td>
                        <td>@(article.IsDeleted ? "Aktif Değil" : "Aktif")</td>
                        <td>
                            <a class="btn btn-success btn-sm center-btn" data-id="@article.Id" asp-area="Admin" asp-controller="Article" asp-action="UndoDelete" asp-route-articleId="@article.Id">
                                <i class='bx bx-undo'></i>
                            </a>


                            @* <a class="btn btn-danger btn-sm" data-id="@article.Id" asp-area="Admin" asp-controller="Article" asp-action="Delete" asp-route-articleId="@article.Id"><i class="bx bx-minus-circle"></i></a> *@
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
    <!--/ Basic Bootstrap Table -->
    
</div>

<style>
    .center-btn {
        display: flex;
        justify-content: center;
        align-items: center;
    }

</style>

@section Scripts{
    <script src="~/js/articleIndex.js" type="application/ecmascript"></script>
}

Blog.Web/Areas/Admin/Views/Category/Add.cshtml
@model CategoryAddDto
<div class="container-xxl flex-grow-1 container-p-y">


    <h4 class="fw-bold py-3 mb-4">
        <span class="text-muted fw-light">Kategori Yönetimi /</span> Kategori Ekle
    </h4>

    <div class="row">
        <div class="col-md-12">
            <div class="card mb-4">
                <h5 class="card-header"></h5>
                <form asp-controller="Category" asp-action="Add" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly"></div>
                    <div class="card-body">
                        
                        <div class="form-group">
                            <label asp-for="Name" id="defaultFormControlInput" class="form-label">Kategori ismi</label>
                            <input asp-for="Name" type="text" class="form-control mb-3" id="defaultFormControlInput" placeholder="Lütfen kategori ismini giriniz." aria-describedby="defaultFormControlHelp">
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>


                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">Kaydet</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


</div>

Blog.Web/Areas/Admin/Views/Shared/_Layout.cshtml
@using Blog.Web.Areas.Admin.ViewComponents
<html lang="en" class="light-style layout-menu-fixed " dir="ltr" data-theme="theme-default" data-template="vertical-menu-template-free">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"/>

    <title>Admin Paneli</title>
    <meta name="description" content="Most Powerful &amp; Comprehensive Bootstrap 5 HTML Admin Dashboard Template built for developers!"/>
    <meta name="keywords" content="dashboard, bootstrap 5 dashboard, bootstrap 5 design, bootstrap 5">
    <link rel="canonical" href="https://themeselection.com/products/sneat-bootstrap-html-admin-template/">
    <link rel="icon" type="image/x-icon" href="~/sneat/assets/img/favicon/favicon.ico"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous"/>
    <link rel="stylesheet" href="~/sneat/assets/vendor/fonts/boxicons.css"/>
    <link rel="stylesheet" href="~/sneat/assets/vendor/css/core.css" class="template-customizer-core-css"/>
    <link rel="stylesheet" href="~/sneat/assets/vendor/css/theme-default.css" class="template-customizer-theme-css"/>
    <link rel="stylesheet" href="~/sneat/assets/css/demo.css"/>
    <link rel="stylesheet" href="~/sneat/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css"/>
    <link rel="stylesheet" href="~/sneat/assets/vendor/libs/apex-charts/apex-charts.css"/>
    <script src="~/sneat/assets/vendor/js/helpers.js"></script>
    <script src="~/sneat/assets/js/config.js"></script>

    <script async="async" src="https://www.googletagmanager.com/gtag/js?id=GA_MEASUREMENT_ID"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        gtag('config', 'GA_MEASUREMENT_ID');
    </script>
</head>

<body>
<!-- Layout wrapper -->
<div class="layout-wrapper layout-content-navbar  ">
    <div class="layout-container">

        <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
            <!-- Logo and Name Section -->
            <div class="menu-logo d-flex align-items-center justify-content-center my-3">
                <img src="~/images/BlogTea.png" alt="Logo" style="height: 50px; margin-right: 15px; border-radius: 50%">
                <span class="menu-logo-text" style="font-size: 1.25rem; font-weight: bold;">Admin Paneli</span>
            </div>
            <ul class="menu-inner py-1">
                <!-- Dashboard -->
                <li class="menu-item active">
                    <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="menu-link">
                        <i class='menu-icon bx bxs-dashboard'></i>
                        <div data-i18n="Analytics">Gösterge Paneli</div>
                    </a>
                </li>

                <li class="menu-header small text-uppercase">
                    <span class="menu-header-text">SAYFA YÖNETİMİ</span>
                </li>
                
                <li class="menu-item">
                    <a asp-area="Admin" asp-controller="Article" asp-action="Index" class="menu-link">
                        <i class='menu-icon bx bx-paper-plane'></i>
                        <div data-i18n="Analytics">Makale Yönetimi</div>
                    </a>
                </li>

                <li class="menu-item">
                    <a asp-area="Admin" asp-controller="Category" asp-action="Index" class="menu-link">
                        <i class='menu-icon bx bx-category'></i>
                        <div data-i18n="Analytics">Kategori Yönetimi</div>
                    </a>
                </li>
                
                <li class="menu-item">
                    <a asp-area="Admin" asp-controller="SocialMedia" asp-action="Index" class="menu-link">
                        <i class='menu-icon bx bx-cube-alt'></i>
                        <div data-i18n="Analytics">Medya Yönetimi</div>
                    </a>
                </li>
                
                <li class="menu-header small text-uppercase">
                    <span class="menu-header-text">KULLANICILAR</span>
                </li>
                
                <li class="menu-item">
                    <a asp-area="Admin" asp-controller="User" asp-action="Index" class="menu-link">
                        <i class="menu-icon tf-icons bx bx-user"></i>
                        <div data-i18n="Basic">Kullanıcılar</div>
                    </a>
                </li>

                <li class="menu-header small text-uppercase">
                    <span class="menu-header-text">Ayarlar</span>
                </li>
                
                <li class="menu-item">
                    <a asp-area="Admin" asp-controller="Smpt" asp-action="Index" class="menu-link">
                        <i class="menu-icon tf-icons bx bx-cog"></i>
                        <div data-i18n="Tables">Smtp Ayarları</div>
                    </a>
                </li>
               
                <li class="menu-header small text-uppercase">
                    <span class="menu-header-text">ÇÖP KUTUSU</span>
                </li>
                
                <li class="menu-item">
                    <a href="javascript:void(0);" class="menu-link menu-toggle">
                        <i class="menu-icon tf-icons bx bx-trash"></i>
                        <div data-i18n="Account Settings">Silinmiş Öğeler</div>
                    </a>
                    <ul class="menu-sub">
                        <li class="menu-item">
                            <a asp-area="Admin" asp-controller="Article" asp-action="DeletedArticles" class="menu-link">
                                <div data-i18n="Account">Makale</div>
                            </a>
                        </li>
                        <li class="menu-item">
                            <a asp-area="Admin" asp-controller="Category" asp-action="DeletedCategories" class="menu-link">
                                <div data-i18n="Notifications">Kategori</div>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </aside>
        <!-- / Menu -->
        <!-- Layout container -->
        <div class="layout-page">

            <!-- Navbar -->

            <nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme" id="layout-navbar">


                <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0   d-xl-none ">
                    <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                        <i class="bx bx-menu bx-sm"></i>
                    </a>
                </div>


                <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
                    
                    <ul class="navbar-nav flex-row align-items-center ms-auto">

                        @await Component.InvokeAsync("DashboardHeader")

                    </ul>
                </div>

            </nav>

            @RenderBody()
        </div>
    </div>
    
    <div class="layout-overlay layout-menu-toggle"></div>

</div>


<script src="~/sneat/assets/vendor/libs/jquery/jquery.js"></script>
<script src="~/sneat/assets/vendor/libs/popper/popper.js"></script>
<script src="~/sneat/assets/vendor/js/bootstrap.js"></script>
<script src="~/sneat/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
<script src="~/sneat/assets/vendor/js/menu.js"></script>
<script src="~/sneat/assets/vendor/libs/apex-charts/apexcharts.js"></script>
<script src="~/sneat/assets/js/main.js"></script>
<script src="~/sneat/assets/js/dashboards-analytics.js"></script>
@await RenderSectionAsync("Scripts", false);
@await Component.InvokeAsync("NToastNotify")
<script async defer src="https://buttons.github.io/buttons.js"></script>
</body>
</html>
    

Blog.Web/Views/Home/ArticleDetail.cshtml
@model ArticleDto

<div style="height: 40px"></div>

<section class="blog-posts">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="all-blog-posts">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="blog-post">
                                <div class="blog-thumb">
                                    <img src="~/stand-blog/assets/images/blog-post-01.jpg" alt="">
                                </div>
                                <div class="down-content">
                                    <a href="#">
                                        <h4>@Model.Title</h4>
                                    </a>
                                    <ul class="post-info">
                                        <li>@Model.User.FirstName @Model.User.LastName</li>
                                        <li>@Model.CreatedDate.ToString("dd/MM/yyyy")</li>
                                        <li>
                                            <i class="fa-solid fa-eye"></i> @Model.ViewCount
                                        </li>
                                    </ul>
                                    <p>
                                        @Model.Content
                                    </p>
                                    <div class="post-options">
                                        <div class="row">
                                            <div class="col-6">
                                                <ul class="post-tags">
                                                    <li>
                                                        <i class="fa fa-tags"></i>
                                                    </li>
                                                    <li>
                                                        <a href="#">@Model.Category.Name</a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    @* @await Component.InvokeAsync("Comments") *@
                    <div class="col-lg-12 mt-4">
                        <div class="comment-section">
                            <h4>Yorum Yapın</h4>
                            <form id="commentForm" action="@Url.Action("SendComment", "Comment", new {area = "User"})" method="post">
                                <div class="form-group">
                                    <label for="name">Adınız:</label>
                                    <input type="text" id="name" name="name" class="form-control" required>
                                </div>
                                <div class="form-group">
                                    <label for="email">E-posta Adresiniz:</label>
                                    <input type="email" id="email" name="email" class="form-control" required>
                                </div>
                                <div class="form-group">
                                    <label for="content">Yorumunuz:</label>
                                    <textarea type="text" id="content" name="content" class="form-control" rows="4" required></textarea>
                                </div>
                                <input type="hidden" name="articleId" value="@Model.Id">
                                <button type="submit" class="btn btn-primary">Gönder</button>
                            </form>
                        </div>
                    </div>

                    <div class="col-lg-12 mt-4">
                        <div class="comment-section">
                            <h4>Yorumlar</h4>

                            @if (Model.Comments != null && Model.Comments.Any())
                            {
                                <ul class="list-unstyled">
                                    @foreach (var comment in Model.Comments)
                                    {
                                        <li class="media mb-4">
                                            <div class="media-body">
                                                <h5 class="mt-0 mb-1">@comment.Name</h5>
                                                <small>@comment.Email</small>
                                                <p>@comment.Content</p>
                                                <small>Yorum Tarihi: @comment.CreatedDate.ToString("dd MMMM yyyy HH:mm")</small>
                                            </div>
                                        </li>
                                    }
                                </ul>
                            }
                            else
                            {
                                <p>Henüz yorum yapılmamış.</p>
                            }
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>

<style>
    .comment-section {
        padding: 1rem;
        background: #f9f9f9;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .comment-section h4 {
        margin-bottom: 1rem;
    }

    .form-group {
        margin-bottom: 1rem;
    }

    .form-group label {
        display: block;
        margin-bottom: 0.5rem;
        font-weight: bold;
    }

    .form-group input, .form-group textarea {
        width: 100%;
        padding: 0.8rem;
        border: 1px solid #ddd;
        border-radius: 4px;
        box-sizing: border-box;
    }

    .form-group input:focus, .form-group textarea:focus {
        border-color: #0073e6;
        outline: none;
    }

    .btn-primary {
        background-color: #0073e6;
        color: #fff;
        border: none;
        border-radius: 4px;
        padding: 0.8rem 2rem;
        font-size: 1rem;
        cursor: pointer;
    }

    .btn-primary:hover {
        background-color: #005bb5;
    }
    html, body {
          margin: 0;
          padding: 0;
          height: 100%;
        }
</style>

Blog.Web/Views/Shared/Components/HomeCategories/Default.cshtml
@model List<Blog.Entity.DTOs.Categories.CategoryDto>

<div class="content">
    <ul>
        @foreach (var category in Model)
        {
            <li> <a asp-controller="Home" asp-area="" asp-action="Index" asp-route-categoryId="@category.Id">@category.Name</a></li>
        }
    </ul>
</div>